import dayjs from 'dayjs';
import { ILocations } from 'app/shared/model/locations.model';
import { IRoles } from 'app/shared/model/roles.model';
import { ILeavesOlds } from 'app/shared/model/leaves-olds.model';
import { IDepartments } from 'app/shared/model/departments.model';
import { IBusinessUnits } from 'app/shared/model/business-units.model';
import { IDivisions } from 'app/shared/model/divisions.model';
import { ICompetencies } from 'app/shared/model/competencies.model';
import { IEmploymentStatuses } from 'app/shared/model/employment-statuses.model';
import { IEmploymentTypes } from 'app/shared/model/employment-types.model';
import { IDesignations } from 'app/shared/model/designations.model';
import { IClaimRequestViews } from 'app/shared/model/claim-request-views.model';
import { IClaimRequests } from 'app/shared/model/claim-requests.model';
import { IDealResources } from 'app/shared/model/deal-resources.model';
import { IEmployeeAddresses } from 'app/shared/model/employee-addresses.model';
import { IEmployeeBirthdays } from 'app/shared/model/employee-birthdays.model';
import { IEmployeeCertificates } from 'app/shared/model/employee-certificates.model';
import { IEmployeeComments } from 'app/shared/model/employee-comments.model';
import { IEmployeeCompensation } from 'app/shared/model/employee-compensation.model';
import { IEmployeeContacts } from 'app/shared/model/employee-contacts.model';
import { IEmployeeDetails } from 'app/shared/model/employee-details.model';
import { IEmployeeDocuments } from 'app/shared/model/employee-documents.model';
import { IEmployeeEducation } from 'app/shared/model/employee-education.model';
import { IEmployeeEmergencyContacts } from 'app/shared/model/employee-emergency-contacts.model';
import { IEmployeeFamilyInfo } from 'app/shared/model/employee-family-info.model';
import { IEmployeeJobInfo } from 'app/shared/model/employee-job-info.model';
import { IEmployeeProfileHistoryLogs } from 'app/shared/model/employee-profile-history-logs.model';
import { IEmployeeProjectRatings } from 'app/shared/model/employee-project-ratings.model';
import { IEmployeeProjects } from 'app/shared/model/employee-projects.model';
import { IEmployeeSkills } from 'app/shared/model/employee-skills.model';
import { IEmployeeTalents } from 'app/shared/model/employee-talents.model';
import { IEmployeeWorks } from 'app/shared/model/employee-works.model';
import { IEmploymentHistory } from 'app/shared/model/employment-history.model';
import { IFeedbackQuestions } from 'app/shared/model/feedback-questions.model';
import { IFeedbackRequests } from 'app/shared/model/feedback-requests.model';
import { IFeedbackRespondents } from 'app/shared/model/feedback-respondents.model';
import { IInterviews } from 'app/shared/model/interviews.model';
import { ILeaveDetailAdjustmentLogs } from 'app/shared/model/leave-detail-adjustment-logs.model';
import { ILeaveRequestApprovers } from 'app/shared/model/leave-request-approvers.model';
import { ILeaveRequestsOlds } from 'app/shared/model/leave-requests-olds.model';
import { ILeaves } from 'app/shared/model/leaves.model';
import { INotificationSentEmailLogs } from 'app/shared/model/notification-sent-email-logs.model';
import { IPcRatings } from 'app/shared/model/pc-ratings.model';
import { IPcRatingsTrainings } from 'app/shared/model/pc-ratings-trainings.model';
import { IPerformanceCycleEmployeeRating } from 'app/shared/model/performance-cycle-employee-rating.model';
import { IProjectCycles } from 'app/shared/model/project-cycles.model';
import { IProjectLeadership } from 'app/shared/model/project-leadership.model';
import { IProjects } from 'app/shared/model/projects.model';
import { IRatings } from 'app/shared/model/ratings.model';
import { IUserAttributes } from 'app/shared/model/user-attributes.model';
import { IUserGoals } from 'app/shared/model/user-goals.model';
import { IUserRatings } from 'app/shared/model/user-ratings.model';
import { IUserRatingsRemarks } from 'app/shared/model/user-ratings-remarks.model';
import { IUserRelations } from 'app/shared/model/user-relations.model';
import { IWorkLogs } from 'app/shared/model/work-logs.model';
import { IZEmployeeProjects } from 'app/shared/model/z-employee-projects.model';

export interface IEmployees {
  id?: number;
  firstname?: string | null;
  lastname?: string | null;
  phonenumber?: string | null;
  dateofbirth?: string | null;
  email?: string | null;
  skype?: string | null;
  employeeDesignation?: string | null;
  joiningdate?: string | null;
  area?: string | null;
  leavingdate?: string | null;
  notes?: string | null;
  isactive?: boolean | null;
  googleid?: string | null;
  oracleid?: string | null;
  deptt?: string | null;
  createdat?: string;
  updatedat?: string;
  genderid?: string;
  onprobation?: boolean | null;
  employeeCompetency?: string | null;
  resourcetype?: string | null;
  grade?: string | null;
  subgrade?: string | null;
  imageurl?: string | null;
  resignationdate?: string | null;
  graduationdate?: string | null;
  careerstartdate?: string | null;
  externalexpyears?: number | null;
  externalexpmonths?: number | null;
  placeofbirth?: string | null;
  hireddate?: string | null;
  lasttrackingupdate?: string | null;
  middlename?: string | null;
  grosssalaryContentType?: string | null;
  grosssalary?: string | null;
  fuelallowanceContentType?: string | null;
  fuelallowance?: string | null;
  mobilenumber?: string | null;
  resignationtype?: string | null;
  primaryreasonforleaving?: string | null;
  secondaryreasonforleaving?: string | null;
  noticeperiodduration?: number | null;
  noticeperiodserved?: number | null;
  probationperiodduration?: number | null;
  location?: ILocations | null;
  role?: IRoles | null;
  manager?: IEmployees | null;
  leave?: ILeavesOlds | null;
  department?: IDepartments | null;
  businessunit?: IBusinessUnits | null;
  division?: IDivisions | null;
  competency?: ICompetencies | null;
  employmentstatus?: IEmploymentStatuses | null;
  employmenttype?: IEmploymentTypes | null;
  designation?: IDesignations | null;
  claimrequestviewsEmployees?: IClaimRequestViews[] | null;
  claimrequestsEmployees?: IClaimRequests[] | null;
  dealresourcesEmployees?: IDealResources[] | null;
  employeeaddressesEmployees?: IEmployeeAddresses[] | null;
  employeebirthdaysEmployees?: IEmployeeBirthdays[] | null;
  employeecertificatesEmployees?: IEmployeeCertificates[] | null;
  employeecommentsCommenters?: IEmployeeComments[] | null;
  employeecommentsEmployees?: IEmployeeComments[] | null;
  employeecompensationEmployees?: IEmployeeCompensation[] | null;
  employeecontactsEmployees?: IEmployeeContacts[] | null;
  employeedetailsEmployees?: IEmployeeDetails[] | null;
  employeedocumentsEmployees?: IEmployeeDocuments[] | null;
  employeeeducationEmployees?: IEmployeeEducation[] | null;
  employeeemergencycontactsEmployees?: IEmployeeEmergencyContacts[] | null;
  employeefamilyinfoEmployees?: IEmployeeFamilyInfo[] | null;
  employeejobinfoEmployees?: IEmployeeJobInfo[] | null;
  employeejobinfoReviewmanagers?: IEmployeeJobInfo[] | null;
  employeejobinfoManagers?: IEmployeeJobInfo[] | null;
  employeeprofilehistorylogsEmployees?: IEmployeeProfileHistoryLogs[] | null;
  employeeprojectratingsProjectarchitects?: IEmployeeProjectRatings[] | null;
  employeeprojectratingsProjectmanagers?: IEmployeeProjectRatings[] | null;
  employeeprojectratingsEmployees?: IEmployeeProjectRatings[] | null;
  employeeprojectsEmployees?: IEmployeeProjects[] | null;
  employeeprojectsAssignors?: IEmployeeProjects[] | null;
  employeeskillsEmployees?: IEmployeeSkills[] | null;
  employeetalentsEmployees?: IEmployeeTalents[] | null;
  employeeworksEmployees?: IEmployeeWorks[] | null;
  employeesManagers?: IEmployees[] | null;
  employmenthistoryEmployees?: IEmploymentHistory[] | null;
  feedbackquestionsEmployees?: IFeedbackQuestions[] | null;
  feedbackrequestsEmployees?: IFeedbackRequests[] | null;
  feedbackrequestsLinemanagers?: IFeedbackRequests[] | null;
  feedbackrespondentsEmployees?: IFeedbackRespondents[] | null;
  interviewsEmployees?: IInterviews[] | null;
  leavedetailadjustmentlogsAdjustedbies?: ILeaveDetailAdjustmentLogs[] | null;
  leaverequestapproversUsers?: ILeaveRequestApprovers[] | null;
  leaverequestsoldsManagers?: ILeaveRequestsOlds[] | null;
  leaverequestsoldsEmployees?: ILeaveRequestsOlds[] | null;
  leavesUsers?: ILeaves[] | null;
  notificationsentemaillogsRecipients?: INotificationSentEmailLogs[] | null;
  pcratingsEmployees?: IPcRatings[] | null;
  pcratingstrainingsSuccessorfors?: IPcRatingsTrainings[] | null;
  performancecycleemployeeratingEmployees?: IPerformanceCycleEmployeeRating[] | null;
  performancecycleemployeeratingManagers?: IPerformanceCycleEmployeeRating[] | null;
  projectcyclesAllowedafterduedatebies?: IProjectCycles[] | null;
  projectcyclesArchitects?: IProjectCycles[] | null;
  projectcyclesProjectmanagers?: IProjectCycles[] | null;
  projectleadershipEmployees?: IProjectLeadership[] | null;
  projectsProjectmanagers?: IProjects[] | null;
  ratingsRaters?: IRatings[] | null;
  userattributesUsers?: IUserAttributes[] | null;
  usergoalsUsers?: IUserGoals[] | null;
  userratingsUsers?: IUserRatings[] | null;
  userratingsReviewmanagers?: IUserRatings[] | null;
  userratingsremarksRaters?: IUserRatingsRemarks[] | null;
  userrelationsUsers?: IUserRelations[] | null;
  userrelationsRelatedusers?: IUserRelations[] | null;
  worklogsEmployees?: IWorkLogs[] | null;
  zemployeeprojectsEmployees?: IZEmployeeProjects[] | null;
  zemployeeprojectsAssignors?: IZEmployeeProjects[] | null;
  zemployeeprojectsProjectmanagers?: IZEmployeeProjects[] | null;
}

export const defaultValue: Readonly<IEmployees> = {
  isactive: false,
  onprobation: false,
};
